version: 3.0.{build}-appveyor
image: Visual Studio 2015
configuration:
- Debug
- Release
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  parallel: true
  verbosity: minimal
artifacts:
  - path: '**\*Gwen*.nupkg'